# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_A7qLQiCnTQSSB822YBprnRFjKtk28wj
"""

import numpy as np
import pandas as pd

def get_ukuran_matrix():
  ukuran_matrix=input('masukan ukuran matriks yang diinginkan :')
  ukuran_matrix=int(ukuran_matrix)
  return ukuran_matrix
ukuran=get_ukuran_matrix()
def input_matrix():
  pass
  matrix_get=[]
  for i in range(ukuran):
    entri_each_row=[]
    for j in range(ukuran):
      
      matrix_entry=int(input('masukan ukuran matrix {satu} {dua}'.format(satu=i,dua=j)))
      entri_each_row.append(matrix_entry)
      if j==ukuran-1:
        matrix_get.append(entri_each_row)
      else:
        pass
  return print('inputan matriks persegi kamu adalah \n{matrix}'.format(matrix=np.matrix(matrix_get)))
input_matrix()

